version: '3'
services:
  app:
    build: .
    image: permit_admin_app
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - .:/root/app
    ports:
      - 2040:3000
    depends_on:
      - db
  db:
    image: postgres:12.2
    container_name: permit_admin_db
    environment:
      - POSTGRES_PASSWORD=permitadmindev
    volumes:
      - ./db_data:/var/lib/postgresql/data
